### PR TITLE
Translation Tool copy

### PR DESCRIPTION
**Pull request by shuyusheng**
With squashed changes from https://github.com/shuyusheng/TranslationsBuilder-cmd 

Originally:
https://github.com/PowerBiDevCamp/TranslationsBuilder
Commit a75c3716021aaa28b6a3559fdfafbb28e671f2f7

### CODE REVIEW

**Comment by KennieNP** [comment]
Do we need all 700+ files? 

Or just the code files needed for this project?

**Comment by shuyusheng** [comment]
> Do we need all 700+ files?
> 
> Or just the code files needed for this project?

Ok, I've built the tool dependent on the translation tool but I can make it independent.

**Comment by KennieNP** [comment]
I was mainly referring to docs and images folders, which is not code.

**Comment by shuyusheng** [comment]
> I was mainly referring to docs and images folders, which is not code.

Updated with unrelated source files removed

**Pull request merged**
